name: Test SSH Connection

on:
  push:
    branches:
      - main

jobs:
  test-connection:
    runs-on: ubuntu-latest
    env:
      HOST: ${{ vars.HOST }}         # Defined in repository settings
      USER: ${{ vars.USER }}         # Defined in repository settings
      SSH_PRIVATE_KEY: ${{ vars.SSHKEY }}  # Defined in repository settings
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup SSH keys
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H "$HOST" >> ~/.ssh/known_hosts

      - name: Test SSH connection
        run: ssh "$USER"@"$HOST" 'echo "Connection Successful"'
