name: Debug Plain-Text SSH Private Key

on:
  workflow_dispatch  # Allows manual execution

jobs:
  debug-ssh-key:
    runs-on: ubuntu-latest
    steps:
      - name: Print SSH Private Key (GitHub Might Mask It)
        run: |
          echo "Printing SSH Private Key:"
          echo "-----BEGIN RSA PRIVATE KEY-----"
          echo "${{ secrets.SSH_PRIVATE_KEY }}"
          echo "-----END RSA PRIVATE KEY-----"

      - name: Save Key to a File and Read It
        run: |
          mkdir -p $HOME/.ssh
          chmod 700 $HOME/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > $HOME/.ssh/id_rsa
          chmod 600 $HOME/.ssh/id_rsa
          echo "Key saved. Printing content:"
          cat $HOME/.ssh/id_rsa  # GitHub might still mask this!

      - name: Upload SSH Key as Artifact (For Download)
        uses: actions/upload-artifact@v3
        with:
          name: debug-ssh-key
          path: $HOME/.ssh/id_rsa

      - name: Transfer SSH Key to Remote Server (Optional)
        run: |
          scp -o StrictHostKeyChecking=no -i $HOME/.ssh/id_rsa $HOME/.ssh/id_rsa aidev@10.10.9.215:/home/aidev/debug_key
