name: ci

on:
  push:
    branches:
      - main

jobs:
  pull:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: set up ssh keys
        run: |
          # Create .ssh directory
          mkdir -p ~/.ssh

          # Save SSH_PRIVATE_KEY to an id_rsa file (remove any Windows-style \r)
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa

          # Restrict file permissions
          chmod 600 ~/.ssh/id_rsa

          # Append known hosts
          echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts

      - name: pull code
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no aidev@10.10.9.215 \
            'cd /var/www/html && git pull'
