name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Debug Directory
        run: ls -la  # Check if package.json is present

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test || echo "Skipping tests since none are defined" && exit 0

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Debug SSH Connection
        run: |
          echo "Testing SSH connection..."
          sshpass -p "OccomAiDev_1" ssh -o StrictHostKeyChecking=no aidev@10.10.9.215 "echo 'SSH connection successful'"

      - name: Deploy via SSH
        run: |
          sshpass -p "OccomAiDev_1" ssh -o StrictHostKeyChecking=no aidev@10.10.9.215 << 'EOF'
          cd ~/New_bot
          git pull origin main
          npm install
          pm2 stop proxy || true
          pm2 start proxy.js --name proxy --watch --port 3002
          EOF
