name: Debug Plain-Text SSH Private Key

on:
  workflow_dispatch  # Allows manual execution

jobs:
  debug-ssh-key:
    runs-on: ubuntu-latest
    steps:
      - name: SSH Login Using Inline Private Key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | ssh -i /dev/stdin -o StrictHostKeyChecking=no aidev@10.10.9.215 "echo 'SSH connection successful'"
